<?php

/* COMPUTER: "MARCA" | "PROCESSORE" | "MEMORIA" | "SISTEMA" | "SCHEDA VIDEO" */

/* DESKTOP: "CASE" | "ALIMENTAZIONE" | "RAFFREDDAMENTO"  */

/* PORTATILE: "DISPLAY" | "MOUSEPAD" | "BATTERIA" | "WEBCAM" */


$computers = [
    new Desktop("ASUS", "M2", "MEMORIA", "SISTEMA", "SCHEDAVIDEO", "CASE", "ALIMENTAZIONE", "RAFFREDDAMENTO"),
    new Desktop("ASUS2", "M24", "MEMORIA2", "SISTEMA2", "SCHEDAVIDEO2", "CASE2", "22ALIMENTAZIONE2", "2RAFFREDDAMENTO"),
    new Portatile("ASUS3", "M23", "MEMORIA3", "SISTEMA3323", "SCHEDAVIDEO2333", "DISPLAY", "MOUSEPAD", "BATTERIA", "WEBCAM"),
];
